// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	context "context"
	foo "dic/foo"
)

// Injectors from main.go:

func initializeBaz(ctx context.Context) (foo.Baz, error) {
	fooFoo := foo.ProvideFoo()
	bar := foo.ProvideBar(fooFoo)
	baz, err := foo.ProvideBaz(ctx, bar)
	if err != nil {
		return foo.Baz{}, err
	}
	return baz, nil
}
